services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cfdive-phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME:-cfdiveuser}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - cfdive-network
    depends_on:
      db:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit
    container_name: cfdive-mailpit
    restart: unless-stopped
    ports:
      - "127.0.0.1:8025:8025"
    networks:
      - cfdive-network
